### ISSUE TITLE
Add identity pool and S3 bucket

### ISSUE THREAD

**Issue by madanalogy** [HTXDIF/cep-backend#11]
S3 bucket should be managed by `template.yaml` for evidence storage. Access to the S3 bucket should be via cognito identity pool for per user access. This configuration is the best option for the frontend.

Alternatives considered included having contents accessed via API, i.e. send blob response to requests for data content. The security mechanisms required for this however might be a little complex, probably easier to just set up federated identity access via cognito.

**Comment by madanalogy** [comment]
Identity pool has been set up, only need to add the S3 bucket now and appropriate IAM policies for the lambdas that need S3 access

**Comment by Linettehtx** [comment]
Added the s3 bucket into the cloudformation
