### ISSUE TITLE
Integrate lambda functions via SQS

### ISSUE THREAD

**Issue by madanalogy** [HTXDIF/cep-backend#7]
1. At least 1 queue per feature lambda. 1 queue for post processing. 1 dead letter queue (DLQ).
2. Each new job created should send a message down the correct queue to trigger the feature lambda.
3. Once feature lambda has completed processing, send message down to post processing queue to trigger the post processing lambda.
4. Any errors funnelled into a DLQ. Ideally, add an SNS integration so that the team gets notified when the DLQ receives any messages

References
- https://docs.aws.amazon.com/lambda/latest/dg/with-sqs-example-use-app-spec.html
- https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-sqs.html

**Comment by Linettehtx** [comment]
Can refer to this reference which I thought helped me (SQS Queue Serverless SAM): https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html

**Comment by madanalogy** [comment]
Only left with dead letter queue integration, possibly with a SNS subscription set up so the team gets notified for any DLQ entries. However this is a low priority compared to other current outstanding tasks
