### ISSUE TITLE
Define DB Schema and API Spec

### ISSUE THREAD

**Issue by madanalogy** [HTXDIF/cep-backend#8]
Need to model attribute fields for job db entries. Each job type will also have their own subset of attribute fields. These attributes then need to be parsed from job creation requests.

**Comment by madanalogy** [comment]
Job: {
  id: String/uuid,
  user: String/uuid,
  type: String/Enum,
  CreatedAt: date,
  CompletedAt?: date,
  notifyUser: boolean (default false),
  properties: {TODO}
}

**Comment by Linettehtx** [comment]
Added another column to the DB schema, thinking to note down the source/user input so that in case maybe next time for logging and tracking purpose

**Comment by madanalogy** [comment]
> Added another column to the DB schema, thinking to note down the source/user input so that in case maybe next time for logging and tracking purpose

What do you mean by "source/user input"? What are you logging and why? Why should we specifically use the primary database for logging? What about alternative logging solutions like CloudWatch or having a separate table entirely for logging? 

Lots of questions to think about for something like this, let me know if you have any problems with any of them

**Comment by madanalogy** [comment]
Updated schema above, see https://github.com/HTXDIF/cep-frontend/issues/4#issuecomment-1103421044 for further elaboration

**Comment by madanalogy** [comment]
Updated schema above, see https://github.com/HTXDIF/cep-frontend/issues/4#issuecomment-1103421044 for further elaboration @Linettehtx @bearpolar
